"""\
TXPA/TXLO temperature-based CDF report from flat CSV, STDF, or .std.tar.gz inputs.

Goal
----
Build merged insertion-level CDFs for TXLO/TXPA correlated-power style measurements.
Each insertion/temperature curve merges all wafers available for that insertion.

Supported inputs
----------------
- Flat CSV generated by ``stdf_to_flat_csv.py``
- Raw STDF files: ``.std``, ``.stdf``, ``.std.gz``, ``.stdf.gz``, ``.std.xz``, ...
- Tarballs that contain STDF files: ``.std.tar.gz`` / ``.stdf.tar.gz``

Default behavior
----------------
- No extra pre-correlation is applied.
- Existing raw limits from the flat CSV are used.

Optional behavior
-----------------
- If ``ENABLE_PRE_CORRELATION`` is set to ``True``, the script applies the same
  correlation-factor logic used by the previous flow and, when available, uses
  the correlation-limit spreadsheets.

Notes
-----
- No CLI by design; edit the CONFIG block.
- Outputs are written under ``INPUT_FOLDER / "Outputs"``.
- Filename metadata extraction is heuristic because multiple naming schemes are
  present in the repository.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import bz2
import gzip
import hashlib
import lzma
import math
import pickle
from pathlib import Path
import re
import sys
import tarfile
import tempfile
from typing import Any, Callable, Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# CONFIG (edit as needed)
# -----------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[3]

INPUT_FOLDER = Path(r"C:\UserData\Infineon\TE_CTRX\CTRX_8188_8144\Data_Reviews\FE_Test_D\Test_D33")
MAX_FILES: int | None = None

ENABLE_PRE_CORRELATION = False
TXLO_CORR_XLSX_FE = REPO_ROOT / "CV_ATE_Correlation_TXLO_Power_FE.xlsx"
TXPA_CORR_XLSX_FE = REPO_ROOT / "CV_ATE_Correlation_TXPA_Power_FE.xlsx"
TXPA_CORR_XLSX_BE = REPO_ROOT / "CV_ATE_Correlation_TXPA_Power_BE.xlsx"

TEST_NUMBER_FILTER: set[int] | None = None
PLOT_DPI = 170
MAD_MULTIPLIER: float = 6.0

EXTREMA_FREQS: set[int] = {76, 77, 81}
TARGET_TXLO_LO_IDAC = 112
TARGET_TXPA_LUT = 255

INSERTION_COLORS = {
    "S1": "#d62728",
    "S2": "#1f77b4",
    "S3": "#2ca02c",
    "B1": "#d62728",
    "B2": "#2ca02c",
}

HIGHLIGHT_MIN_COLOR = "#8c564b"
HIGHLIGHT_MAX_COLOR = "#e377c2"


# Make repo root importable even when running this script from another CWD.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))




# -----------------------------------------------------------------------------
# Helpers and metadata models
# -----------------------------------------------------------------------------

_INSERTION_ORDER_FE = ["S1", "S2", "S3"]
_INSERTION_ORDER_BE = ["B1", "B2"]
_TEMP_BY_INS: dict[str, int] = {"S1": 135, "S2": -40, "S3": 25, "B1": 135, "B2": 25}
_INS_TYPE_BY_INS: dict[str, str] = {"S1": "FE", "S2": "FE", "S3": "FE", "B1": "BE", "B2": "BE"}
_FLAT_META_COLS = ["UNIT_ID", "SITE_NUM", "WAFER", "X", "Y", "LOT", "SUBLOT", "CHIP_ID", "PF", "FIRST_FAIL_TEST"]
_SUMMARY_ROW_COUNT = 8

_DIRECT_STDF_SUFFIXES = (
    ".std",
    ".stdf",
    ".std.gz",
    ".stdf.gz",
    ".std.xz",
    ".stdf.xz",
    ".std.bz2",
    ".stdf.bz2",
)
_TAR_STDF_SUFFIXES = (".std.tar.gz", ".stdf.tar.gz")

_TX_PREFIX_RE = re.compile(r"^(?P<blk>TXLO|TXPA|TXPB|TXPC)_(?P<freq>\d+)", flags=re.IGNORECASE)
_FWLU_RE = re.compile(r"FwLu(?P<lut>\d{1,3})(?!\d)", flags=re.IGNORECASE)
_POWCO_RE = re.compile(r"PowCo(?P<idac>\d{1,3})(?!\d)", flags=re.IGNORECASE)
_TX_CH_RE = re.compile(r"Tx(?P<ch>[1-8])(?!\d)", flags=re.IGNORECASE)
_INSERTION_TOKEN_RE = re.compile(r"^(S11P|S21P|S31P|B11P|B21P)$", flags=re.IGNORECASE)


@dataclass(frozen=True)
class InsertionInfo:
    insertion: str
    insertion_type: str
    temperature_c: int


@dataclass(frozen=True)
class SourceFileInfo:
    source_path: Path
    csv_path: Path | None
    source_kind: str
    insertion: str
    insertion_type: str
    temperature_c: int
    lot: str | None
    wafer: str | None
    base_name: str
    direct_power_data: DirectPowerData | None = None


@dataclass(frozen=True)
class DirectPowerData:
    name_map: dict[int, str]
    limits_map: dict[int, tuple[float | None, float | None, str]]
    arrays_by_test: dict[int, np.ndarray]
    n_chips: int
    warnings: tuple[str, ...] = ()


def _direct_cache_signature(path: Path, *, extra_key: str = "") -> dict[str, Any]:
    stat = path.stat()
    return {
        "path": str(path.resolve()),
        "size": int(stat.st_size),
        "mtime_ns": int(getattr(stat, "st_mtime_ns", int(stat.st_mtime * 1_000_000_000))),
        "extra_key": extra_key,
        "target_txlo_lo_idac": int(TARGET_TXLO_LO_IDAC),
        "target_txpa_lut": int(TARGET_TXPA_LUT),
        "test_filter": None if TEST_NUMBER_FILTER is None else sorted(int(value) for value in TEST_NUMBER_FILTER),
    }


def _direct_cache_path(cache_dir: Path, path: Path, *, extra_key: str = "") -> Path:
    base_name = _strip_known_suffixes(path.name)
    token = hashlib.sha1(f"{path.resolve()}::{extra_key}".encode("utf-8", errors="ignore")).hexdigest()[:12]
    return cache_dir / f"{base_name}__{token}.pkl"


def _load_cached_direct_power_data(cache_path: Path, *, signature: dict[str, Any]) -> DirectPowerData | None:
    if not cache_path.exists():
        return None
    try:
        with cache_path.open("rb") as handle:
            payload = pickle.load(handle)
    except Exception:
        return None

    if not isinstance(payload, dict) or payload.get("signature") != signature:
        return None

    data = payload.get("data")
    if not isinstance(data, DirectPowerData):
        return None
    return data


def _save_cached_direct_power_data(cache_path: Path, *, signature: dict[str, Any], data: DirectPowerData) -> None:
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"signature": signature, "data": data}
    with cache_path.open("wb") as handle:
        pickle.dump(payload, handle, protocol=pickle.HIGHEST_PROTOCOL)


@dataclass(frozen=True)
class TestMeta:
    test_number: int
    test_name: str
    kind: str
    frequency_ghz: int | None
    lut_value: int | None
    lo_idac: int | None
    pa_channel: str | None


def _has_any_suffix(path: Path, suffixes: tuple[str, ...]) -> bool:
    name = path.name.lower()
    return any(name.endswith(sfx) for sfx in suffixes)


def _strip_known_suffixes(name: str) -> str:
    lower = name.lower()
    for suffix in sorted(_TAR_STDF_SUFFIXES + _DIRECT_STDF_SUFFIXES + (".csv",), key=len, reverse=True):
        if lower.endswith(suffix):
            return name[: -len(suffix)]
    return Path(name).stem


def _insertion_from_filename(path: Path) -> InsertionInfo | None:
    name_upper = path.name.upper()
    if "S11P" in name_upper:
        return InsertionInfo("S1", "FE", 135)
    if "S21P" in name_upper:
        return InsertionInfo("S2", "FE", -40)
    if "S31P" in name_upper:
        return InsertionInfo("S3", "FE", 25)
    if "B11P" in name_upper:
        return InsertionInfo("B1", "BE", 135)
    if "B21P" in name_upper:
        return InsertionInfo("B2", "BE", 25)
    return None


def _parse_filename_metadata(path: Path, insertion: InsertionInfo) -> tuple[str | None, str | None]:
    _ = insertion
    stem = _strip_known_suffixes(path.name)
    tokens = [tok for tok in stem.split("_") if tok]
    insertion_idx = next((i for i, tok in enumerate(tokens) if _INSERTION_TOKEN_RE.fullmatch(tok)), None)

    lot: str | None = None
    wafer: str | None = None

    if insertion_idx is not None:
        if insertion_idx >= 2 and re.fullmatch(r"\d+", tokens[1]):
            lot = tokens[0]
            wafer = tokens[1]
            return lot, wafer

        before = tokens[:insertion_idx]
        numeric_before = [tok for tok in before if re.fullmatch(r"\d+", tok)]
        if numeric_before:
            wafer = numeric_before[-1]

        lot_tokens = before.copy()
        if lot_tokens and re.fullmatch(r"\d{14}", lot_tokens[0]):
            lot_tokens = lot_tokens[1:]
        if wafer and lot_tokens and lot_tokens[-1] == wafer:
            lot_tokens = lot_tokens[:-1]
        if lot_tokens:
            lot = "_".join(lot_tokens)

    if not lot and tokens:
        lot = tokens[0]
    return lot, wafer


def _parse_test_meta(test_number: int, test_name: str) -> TestMeta | None:
    name = str(test_name or "").strip()
    match = _TX_PREFIX_RE.match(name)
    if not match:
        return None

    blk = match.group("blk").upper()
    try:
        freq = int(match.group("freq"))
    except Exception:
        freq = None

    lut = None
    lut_match = _FWLU_RE.search(name)
    if lut_match:
        try:
            lut = int(lut_match.group("lut"))
        except Exception:
            lut = None

    lo_idac = None
    lo_match = _POWCO_RE.search(name)
    if lo_match:
        try:
            lo_idac = int(lo_match.group("idac"))
        except Exception:
            lo_idac = None

    pa_channel = None
    channel_match = _TX_CH_RE.search(name)
    if channel_match:
        pa_channel = f"TX{channel_match.group('ch')}"

    kind = "TXLO" if blk == "TXLO" else "TXPA"
    return TestMeta(
        test_number=int(test_number),
        test_name=name,
        kind=kind,
        frequency_ghz=freq,
        lut_value=lut,
        lo_idac=lo_idac,
        pa_channel=pa_channel,
    )


def _stdf_clean_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _stdf_field(record_dict: dict[str, Any], *names: str) -> Any:
    for name in names:
        if name in record_dict:
            return record_dict[name]
    return None


def _stdf_to_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)):
        result = float(value)
        if not np.isfinite(result):
            return None
        return result
    text = str(value).strip()
    if not text or text.lower() in {"nan", "na", "none", "inf", "-inf", "+inf"}:
        return None
    try:
        result = float(text)
    except ValueError:
        try:
            result = float(text.replace(",", "."))
        except ValueError:
            return None
    if not np.isfinite(result):
        return None
    return result


def _stdf_to_int(value: Any) -> int | None:
    number = _stdf_to_float(value)
    if number is None:
        return None
    try:
        return int(number)
    except (TypeError, ValueError, OverflowError):
        return None


def _open_stdf_binary(path: Path):
    suffixes = [suffix.lower() for suffix in path.suffixes]
    if suffixes and suffixes[-1] == ".gz":
        return gzip.open(path, "rb")
    if suffixes and suffixes[-1] == ".bz2":
        return bz2.open(path, "rb")
    if suffixes and suffixes[-1] == ".xz":
        return lzma.open(path, "rb")
    return path.open("rb")


def _get_or_create_virtual_test_number(
    *,
    emitted_by_key: dict[tuple[int, str], int],
    used_ids: set[str],
    base_test_number: int,
    variant: str,
) -> int:
    key = (int(base_test_number), variant)
    existing = emitted_by_key.get(key)
    if existing is not None:
        return existing

    base = str(int(base_test_number))
    if base not in used_ids:
        used_ids.add(base)
        emitted = int(base)
    else:
        duplicate_index = 1
        while True:
            candidate = f"{base}{duplicate_index:03d}"
            if candidate not in used_ids:
                used_ids.add(candidate)
                emitted = int(candidate)
                break
            duplicate_index += 1

    emitted_by_key[key] = emitted
    return emitted


def _collect_target_power_data_from_stdf(
    stdf_path: Path,
    *,
    progress_callback: Callable[[float, str], None] | None = None,
) -> DirectPowerData:
    try:
        import pystdf.V4 as V4
        from pystdf.IO import Parser
    except ImportError as exc:
        raise RuntimeError(
            "STDF parsing requires the 'pystdf' package. Install it from the current virtual environment."
        ) from exc

    name_map: dict[int, str] = {}
    limits_map: dict[int, tuple[float | None, float | None, str]] = {}
    values_by_test: dict[int, list[float]] = {}
    emitted_by_key: dict[tuple[int, str], int] = {}
    used_ids: set[str] = set()
    active_sites: set[int | None] = set()
    warnings: list[str] = []
    n_chips = 0

    source_size = None
    try:
        if stdf_path.is_file() and not any(str(stdf_path.name).lower().endswith(suffix) for suffix in (".gz", ".bz2", ".xz")):
            source_size = max(int(stdf_path.stat().st_size), 1)
    except OSError:
        source_size = None

    with _open_stdf_binary(stdf_path) as handle:
        last_fraction_reported = -1.0

        def report_progress(force: bool = False, suffix: str = "") -> None:
            nonlocal last_fraction_reported
            if progress_callback is None or source_size is None:
                return
            try:
                fraction = max(0.0, min(1.0, float(handle.tell()) / float(source_size)))
            except Exception:
                return
            if force or fraction - last_fraction_reported >= 0.05:
                last_fraction_reported = fraction
                message = f"Streaming STDF {stdf_path.name}"
                if suffix:
                    message = f"{message} - {suffix}"
                progress_callback(fraction, message)

        class _PowerParser(Parser):
            def __init__(self, inp) -> None:
                super().__init__(recTypes=(V4.far, V4.mir, V4.wir, V4.pir, V4.ptr, V4.mpr, V4.prr), inp=inp)

            def parse_records(self, count=0):
                i = 0
                self.eof = 0
                while self.eof == 0:
                    try:
                        header = self.readHeader()
                    except Exception as exc:
                        if exc.__class__.__name__ == "EofException":
                            break
                        raise

                    self.header(header)
                    if (header.typ, header.sub) in self.recordMap:
                        rec_type = self.recordMap[(header.typ, header.sub)]
                        rec_parser = self.recordParsers[(header.typ, header.sub)]
                        try:
                            fields = rec_parser(self, header, [])
                        except Exception as exc:
                            record_name = rec_type.__class__.__name__.upper()
                            warnings.append(f"Skipped malformed {record_name} record in {stdf_path.name}: {exc}")
                            if header.len > 0:
                                self.inp.read(header.len)
                                header.len = 0
                            continue

                        if len(fields) < len(rec_type.columnNames):
                            fields += [None] * (len(rec_type.columnNames) - len(fields))
                        self.send((rec_type, fields))
                        if header.len > 0:
                            self.inp.read(header.len)
                            header.len = 0
                    else:
                        self.inp.read(header.len)

                    report_progress()
                    if count:
                        i += 1
                        if i >= count:
                            break

            def send(self, data) -> None:
                nonlocal n_chips

                rec_type, fields = data
                record_name = rec_type.__class__.__name__.upper()
                record_dict = {name: value for name, value in zip(getattr(rec_type, "fieldNames", []), fields)}

                if record_name == "PIR":
                    active_sites.add(_stdf_to_int(_stdf_field(record_dict, "SITE_NUM")))
                    return

                if record_name == "PRR":
                    active_sites.discard(_stdf_to_int(_stdf_field(record_dict, "SITE_NUM")))
                    n_chips += 1
                    return

                if record_name not in {"PTR", "MPR"}:
                    return

                test_num = _stdf_to_int(_stdf_field(record_dict, "TEST_NUM"))
                if test_num is None:
                    return

                test_name = _stdf_clean_text(_stdf_field(record_dict, "TEST_TXT", "TEST_NAM", "VECT_NAM")) or str(test_num)
                unit = _stdf_clean_text(_stdf_field(record_dict, "UNITS", "UNIT")) or ""
                low = _stdf_to_float(_stdf_field(record_dict, "LO_LIMIT", "LLM", "LOW_LIMIT"))
                high = _stdf_to_float(_stdf_field(record_dict, "HI_LIMIT", "HLM", "HIGH_LIMIT"))

                def append_value(*, virtual_test_number: int, final_test_name: str, result: float | None) -> None:
                    meta = _parse_test_meta(virtual_test_number, final_test_name)
                    if not _is_target_power_test(meta):
                        return
                    if not _is_selected_power_setting(meta):
                        return
                    if not _is_dbm_unit(unit):
                        return
                    if TEST_NUMBER_FILTER and int(virtual_test_number) not in TEST_NUMBER_FILTER:
                        return
                    if result is None:
                        return

                    name_map[virtual_test_number] = final_test_name
                    existing_low, existing_high, existing_unit = limits_map.get(virtual_test_number, (None, None, ""))
                    limits_map[virtual_test_number] = (
                        low if existing_low is None else existing_low,
                        high if existing_high is None else existing_high,
                        unit or existing_unit,
                    )
                    values_by_test.setdefault(virtual_test_number, []).append(float(result))

                if record_name == "PTR":
                    virtual_test_number = _get_or_create_virtual_test_number(
                        emitted_by_key=emitted_by_key,
                        used_ids=used_ids,
                        base_test_number=int(test_num),
                        variant="PTR",
                    )
                    append_value(
                        virtual_test_number=virtual_test_number,
                        final_test_name=test_name,
                        result=_stdf_to_float(_stdf_field(record_dict, "RESULT")),
                    )
                    return

                results_raw = _stdf_field(record_dict, "RTN_RSLT", "RESULTS")
                if isinstance(results_raw, (list, tuple)):
                    results = [_stdf_to_float(value) for value in results_raw]
                else:
                    single_result = _stdf_to_float(results_raw)
                    results = [single_result] if single_result is not None else []
                if not results:
                    return

                pin_labels_raw = _stdf_field(record_dict, "RTN_INDX", "RTN_STAT", "PMR_INDX")
                if isinstance(pin_labels_raw, (list, tuple)):
                    pin_labels = [str(item) for item in pin_labels_raw]
                else:
                    pin_labels = []

                for result_index, result in enumerate(results, start=1):
                    pin_suffix = pin_labels[result_index - 1] if result_index - 1 < len(pin_labels) and pin_labels[result_index - 1] else str(result_index)
                    expanded_name = f"{test_name}[{pin_suffix}]"
                    virtual_test_number = _get_or_create_virtual_test_number(
                        emitted_by_key=emitted_by_key,
                        used_ids=used_ids,
                        base_test_number=int(test_num),
                        variant=f"MPR:{pin_suffix}",
                    )
                    append_value(
                        virtual_test_number=virtual_test_number,
                        final_test_name=expanded_name,
                        result=result,
                    )

        report_progress(force=True, suffix="0%")
        _PowerParser(handle).parse()
        report_progress(force=True, suffix="100%")

    if active_sites:
        n_chips += len(active_sites)

    arrays_by_test = {
        int(test_number): np.asarray(values, dtype=float)
        for test_number, values in values_by_test.items()
        if values
    }
    return DirectPowerData(
        name_map=name_map,
        limits_map=limits_map,
        arrays_by_test=arrays_by_test,
        n_chips=int(n_chips),
        warnings=tuple(warnings),
    )


def _load_or_collect_target_power_data(
    stdf_path: Path,
    *,
    cache_dir: Path,
    cache_extra_key: str = "",
    progress_callback: Callable[[float, str], None] | None = None,
) -> DirectPowerData:
    signature = _direct_cache_signature(stdf_path, extra_key=cache_extra_key)
    cache_path = _direct_cache_path(cache_dir, stdf_path, extra_key=cache_extra_key)
    cached = _load_cached_direct_power_data(cache_path, signature=signature)
    if cached is not None:
        if progress_callback is not None:
            progress_callback(1.0, f"Loaded cached STDF slice for {stdf_path.name}")
        return cached

    data = _collect_target_power_data_from_stdf(stdf_path, progress_callback=progress_callback)
    _save_cached_direct_power_data(cache_path, signature=signature, data=data)
    return data


def _is_target_power_test(meta: TestMeta | None) -> bool:
    if meta is None:
        return False
    if meta.kind == "TXLO":
        return meta.lo_idac is not None
    return meta.lut_value is not None


def _is_selected_power_setting(meta: TestMeta | None) -> bool:
    if meta is None:
        return False
    if meta.kind == "TXLO":
        return meta.lo_idac == int(TARGET_TXLO_LO_IDAC)
    if meta.kind == "TXPA":
        return meta.lut_value == int(TARGET_TXPA_LUT)
    return False


def _is_dbm_unit(unit: str | None) -> bool:
    return str(unit or "").strip().upper() == "DBM"


def _cdf_xy(values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return np.array([], dtype=float), np.array([], dtype=float)
    x = np.sort(arr)
    y = np.arange(1, arr.size + 1, dtype=float) / float(arr.size)
    return x, y


def _median(values: np.ndarray) -> float:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return float("nan")
    return float(np.median(arr))


def _filter_outliers_mad(values: np.ndarray, *, mad_multiplier: float) -> tuple[np.ndarray, int]:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size < 5:
        return arr, 0
    med = float(np.median(arr))
    abs_dev = np.abs(arr - med)
    mad = float(np.median(abs_dev))
    if not np.isfinite(mad) or mad <= 0.0:
        return arr, 0
    keep = abs_dev <= float(mad_multiplier) * mad
    filtered = arr[keep]
    return filtered, int(arr.size - filtered.size)


def _read_flat_csv_metadata(path: Path) -> tuple[dict[int, str], dict[int, tuple[float | None, float | None, str]]]:
    with path.open("r", encoding="latin1", errors="ignore") as handle:
        rows = [handle.readline().rstrip("\n\r").split(";") for _ in range(5)]

    if len(rows) < 5 or not rows[0]:
        return {}, {}

    header, test_names, lows, highs, units = rows
    max_len = max(len(header), len(test_names), len(lows), len(highs), len(units))
    rows_norm = []
    for row in (header, test_names, lows, highs, units):
        rows_norm.append(row + [""] * (max_len - len(row)))
    header, test_names, lows, highs, units = rows_norm

    name_map: dict[int, str] = {}
    limits_map: dict[int, tuple[float | None, float | None, str]] = {}

    for col_id, test_name, low_text, high_text, unit in zip(header, test_names, lows, highs, units, strict=False):
        col_id = str(col_id).strip()
        if not col_id.isdigit():
            continue
        test_number = int(col_id)
        name_map[test_number] = str(test_name).strip()

        low = pd.to_numeric(low_text, errors="coerce")
        high = pd.to_numeric(high_text, errors="coerce")
        limits_map[test_number] = (
            float(low) if pd.notna(low) else None,
            float(high) if pd.notna(high) else None,
            str(unit).strip(),
        )

    return name_map, limits_map


def _read_flat_csv_chip_matrix(path: Path, *, tests_needed: Iterable[int] | None = None) -> tuple[pd.DataFrame, dict]:
    wanted: set[int] | None = None
    if tests_needed is not None:
        wanted = {int(t) for t in tests_needed}

    with path.open("r", encoding="latin1", errors="ignore") as handle:
        header = handle.readline().rstrip("\n\r").split(";")

    normalized_header = [str(col).strip() for col in header]
    usecols: list[str] | None = None
    if wanted:
        usecols = [col for col in normalized_header if col in _FLAT_META_COLS or (col.isdigit() and int(col) in wanted)]
        if len(usecols) < 2:
            usecols = None

    df = pd.read_csv(
        path,
        sep=";",
        header=0,
        skiprows=range(1, _SUMMARY_ROW_COUNT + 1),
        usecols=usecols,
        encoding="latin1",
        low_memory=False,
    )

    if df.empty:
        return pd.DataFrame(), {"error": "no_chip_rows"}

    test_cols = [col for col in df.columns if str(col).isdigit()]
    if not test_cols:
        return pd.DataFrame(), {"error": "test_cols_not_found"}

    values = df[test_cols].apply(pd.to_numeric, errors="coerce")
    values.columns = [int(col) for col in values.columns]

    chip_id = None
    if "CHIP_ID" in df.columns:
        chip_id = df["CHIP_ID"].astype(str).str.strip().replace({"": np.nan})
    if chip_id is None or chip_id.isna().all():
        parts: list[pd.Series] = []
        for col in ("LOT", "WAFER", "X", "Y", "UNIT_ID"):
            if col in df.columns:
                parts.append(df[col].astype(str).str.strip())
        if parts:
            chip_id = parts[0]
            for extra in parts[1:]:
                chip_id = chip_id + ":" + extra
        else:
            chip_id = pd.Series([str(i) for i in range(len(df))], index=df.index)

    chip_matrix = values.copy()
    chip_matrix.index = chip_id.astype(str)
    return chip_matrix, {"error": "", "n_tests": int(chip_matrix.shape[1]), "n_chips": int(chip_matrix.shape[0])}


# -----------------------------------------------------------------------------
# Optional correlation lookup loading
# -----------------------------------------------------------------------------


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df is None or df.empty:
        return df
    df = df.copy()
    df.columns = [str(col).replace("\n", "").strip() for col in df.columns]
    return df


def _parse_test_number_cell(cell) -> list[int]:
    if cell is None or (isinstance(cell, float) and math.isnan(cell)):
        return []
    if isinstance(cell, (int, np.integer)):
        return [int(cell)]
    if isinstance(cell, float) and float(cell).is_integer():
        return [int(cell)]
    text = str(cell).strip()
    if not text:
        return []
    match = re.fullmatch(r"(?P<a>\d+)\s*-\s*(?P<b>\d+)", text)
    if match:
        start = int(match.group("a"))
        stop = int(match.group("b"))
        if start > stop:
            start, stop = stop, start
        return list(range(start, stop + 1))
    if text.isdigit():
        return [int(text)]
    return []


def _load_txlo_factors_and_limits() -> tuple[dict[tuple[int, int, int, int], float], dict[tuple[int, int, int], dict[str, tuple[float, float, str]]]]:
    fac = _normalize_columns(pd.read_excel(TXLO_CORR_XLSX_FE, sheet_name="Correlation_Factors"))
    lim = _normalize_columns(pd.read_excel(TXLO_CORR_XLSX_FE, sheet_name="Correlation_Limits"))

    fac["Test Number"] = pd.to_numeric(fac["Test Number"], errors="coerce").astype("Int64")
    fac["Frequency_GHz"] = pd.to_numeric(fac["Frequency_GHz"], errors="coerce").astype("Int64")
    fac["Temperature"] = pd.to_numeric(fac["Temperature"], errors="coerce").astype("Int64")
    fac["LO IDAC"] = pd.to_numeric(fac["LO IDAC"], errors="coerce").astype("Int64")

    factor_lookup: dict[tuple[int, int, int, int], float] = {}
    for _, row in fac.iterrows():
        if pd.isna(row.get("Test Number")) or pd.isna(row.get("Frequency_GHz")) or pd.isna(row.get("Temperature")) or pd.isna(row.get("LO IDAC")):
            continue
        delta = pd.to_numeric(row.get("MedianDelta(CV-ATE)"), errors="coerce")
        if pd.isna(delta):
            continue
        factor_lookup[(int(row["Test Number"]), int(row["Frequency_GHz"]), int(row["Temperature"]), int(row["LO IDAC"]))] = float(delta)

    lim["Test Number"] = pd.to_numeric(lim["Test Number"], errors="coerce").astype("Int64")
    lim["Frequency_GHz"] = pd.to_numeric(lim["Frequency_GHz"], errors="coerce").astype("Int64")
    lim["LO IDAC"] = pd.to_numeric(lim["LO IDAC"], errors="coerce").astype("Int64")

    limits_lookup: dict[tuple[int, int, int], dict[str, tuple[float, float, str]]] = {}
    for _, row in lim.iterrows():
        if pd.isna(row.get("Test Number")) or pd.isna(row.get("Frequency_GHz")) or pd.isna(row.get("LO IDAC")):
            continue
        item: dict[str, tuple[float, float, str]] = {}
        unit = str(row.get("Unit") or "dBm").strip() or "dBm"
        for insertion in _INSERTION_ORDER_FE:
            low = pd.to_numeric(row.get(f"Corr_Low ({insertion})"), errors="coerce")
            high = pd.to_numeric(row.get(f"Corr_High ({insertion})"), errors="coerce")
            if pd.notna(low) and pd.notna(high):
                item[insertion] = (float(low), float(high), unit)
        limits_lookup[(int(row["Test Number"]), int(row["Frequency_GHz"]), int(row["LO IDAC"]))] = item
    return factor_lookup, limits_lookup


def _load_txpa_factors_and_limits_fe() -> tuple[
    dict[tuple[int, int, int, str], float],
    dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]],
]:
    fac = _normalize_columns(pd.read_excel(TXPA_CORR_XLSX_FE, sheet_name="Correlation_Factors"))
    lim = _normalize_columns(pd.read_excel(TXPA_CORR_XLSX_FE, sheet_name="Correlation_Limits"))

    fac["LUT value"] = pd.to_numeric(fac["LUT value"], errors="coerce").astype("Int64")
    fac["Frequency_GHz"] = pd.to_numeric(fac["Frequency_GHz"], errors="coerce").astype("Int64")
    fac["Temperature"] = pd.to_numeric(fac["Temperature"], errors="coerce").astype("Int64")
    fac["PA Channel"] = fac.get("PA Channel", "ALL").astype(str).str.strip().replace({"": "ALL"})

    factor_lookup: dict[tuple[int, int, int, str], float] = {}
    for _, row in fac.iterrows():
        if pd.isna(row.get("LUT value")) or pd.isna(row.get("Frequency_GHz")) or pd.isna(row.get("Temperature")):
            continue
        delta = pd.to_numeric(row.get("MedianDelta(CV-ATE)"), errors="coerce")
        if pd.isna(delta):
            continue
        factor_lookup[(int(row["LUT value"]), int(row["Frequency_GHz"]), int(row["Temperature"]), str(row.get("PA Channel") or "ALL").strip().upper() or "ALL")] = float(delta)

    lim["LUT value"] = pd.to_numeric(lim["LUT value"], errors="coerce").astype("Int64")
    lim["Frequency_GHz"] = pd.to_numeric(lim["Frequency_GHz"], errors="coerce").astype("Int64")
    lim["PA Channel"] = lim.get("PA Channel", "ALL").astype(str).str.strip().replace({"": "ALL"})

    limits_lookup: dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]] = {}
    for _, row in lim.iterrows():
        if pd.isna(row.get("LUT value")) or pd.isna(row.get("Frequency_GHz")):
            continue
        unit = str(row.get("Unit") or "dBm").strip() or "dBm"
        channels = str(row.get("PA Channel") or "ALL").strip().upper() or "ALL"
        insertions: dict[str, tuple[float, float, str]] = {}
        for insertion in _INSERTION_ORDER_FE:
            low = pd.to_numeric(row.get(f"Corr_Low ({insertion})"), errors="coerce")
            high = pd.to_numeric(row.get(f"Corr_High ({insertion})"), errors="coerce")
            if pd.notna(low) and pd.notna(high):
                insertions[insertion] = (float(low), float(high), unit)
        for test_number in _parse_test_number_cell(row.get("Test Number")):
            limits_lookup[(int(test_number), int(row["Frequency_GHz"]), int(row["LUT value"]), channels)] = insertions
    return factor_lookup, limits_lookup


def _load_txpa_factors_and_limits_be() -> tuple[
    dict[tuple[int, int, int, str], float],
    dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]],
]:
    fac = _normalize_columns(pd.read_excel(TXPA_CORR_XLSX_BE, sheet_name="Correlation_Factors"))
    lim = _normalize_columns(pd.read_excel(TXPA_CORR_XLSX_BE, sheet_name="Correlation_Limits"))

    fac["LUT value"] = pd.to_numeric(fac["LUT value"], errors="coerce").astype("Int64")
    fac["Frequency_GHz"] = pd.to_numeric(fac["Frequency_GHz"], errors="coerce").astype("Int64")
    fac["Temperature"] = pd.to_numeric(fac["Temperature"], errors="coerce").astype("Int64")
    fac["PA Channel"] = fac.get("PA Channel", "ALL").astype(str).str.strip().replace({"": "ALL"})
    fac["Voltage corner"] = fac.get("Voltage corner", "VMIN").astype(str).str.strip().replace({"": "VMIN"})

    fac = fac.loc[fac["Voltage corner"].astype(str).str.upper().eq("VMIN")].copy()

    factor_lookup: dict[tuple[int, int, int, str], float] = {}
    grouped = fac.dropna(subset=["LUT value", "Frequency_GHz", "Temperature", "MedianDelta(CV-ATE)"]).groupby(
        ["LUT value", "Frequency_GHz", "Temperature", "PA Channel"], dropna=True
    )["MedianDelta(CV-ATE)"].median()
    for (lut, freq, temp, channel), delta in grouped.items():
        factor_lookup[(int(lut), int(freq), int(temp), str(channel).strip().upper() or "ALL")] = float(delta)

    lim["LUT value"] = pd.to_numeric(lim["LUT value"], errors="coerce").astype("Int64")
    lim["Frequency_GHz"] = pd.to_numeric(lim["Frequency_GHz"], errors="coerce").astype("Int64")
    lim["PA Channel"] = lim.get("PA Channel", "ALL").astype(str).str.strip().replace({"": "ALL"})

    limits_lookup: dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]] = {}
    for _, row in lim.iterrows():
        if pd.isna(row.get("LUT value")) or pd.isna(row.get("Frequency_GHz")):
            continue
        unit = str(row.get("Unit") or "dBm").strip() or "dBm"
        channel = str(row.get("PA Channel") or "ALL").strip().upper() or "ALL"
        insertions: dict[str, tuple[float, float, str]] = {}
        for insertion in _INSERTION_ORDER_BE:
            low = pd.to_numeric(row.get(f"Corr_Low ({insertion})"), errors="coerce")
            high = pd.to_numeric(row.get(f"Corr_High ({insertion})"), errors="coerce")
            if pd.notna(low) and pd.notna(high):
                insertions[insertion] = (float(low), float(high), unit)
        for test_number in _parse_test_number_cell(row.get("Test Number")):
            limits_lookup[(int(test_number), int(row["Frequency_GHz"]), int(row["LUT value"]), channel)] = insertions
    return factor_lookup, limits_lookup


def _lookup_txpa_factor(
    factor_lookup: dict[tuple[int, int, int, str], float],
    *,
    lut: int,
    freq: int,
    temp_c: int,
    pa_channel: str | None,
) -> float | None:
    channel = (pa_channel or "ALL").strip().upper() or "ALL"
    exact = (int(lut), int(freq), int(temp_c), channel)
    all_channel = (int(lut), int(freq), int(temp_c), "ALL")
    if exact in factor_lookup:
        return factor_lookup[exact]
    if all_channel in factor_lookup:
        return factor_lookup[all_channel]
    return None


def _lookup_txpa_limits(
    limits_lookup: dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]],
    *,
    test_number: int,
    lut: int,
    freq: int,
    pa_channel: str | None,
) -> dict[str, tuple[float, float, str]]:
    channel = (pa_channel or "ALL").strip().upper() or "ALL"
    exact = (int(test_number), int(freq), int(lut), channel)
    all_channel = (int(test_number), int(freq), int(lut), "ALL")
    if exact in limits_lookup:
        return limits_lookup[exact]
    if all_channel in limits_lookup:
        return limits_lookup[all_channel]
    return {}


# -----------------------------------------------------------------------------
# Input preparation
# -----------------------------------------------------------------------------


def _extract_stdf_members_from_tar(archive_path: Path, destination: Path) -> list[Path]:
    extracted: list[Path] = []
    destination.mkdir(parents=True, exist_ok=True)
    with tarfile.open(archive_path, mode="r:gz") as archive:
        for member in archive.getmembers():
            if not member.isfile():
                continue
            member_name = Path(member.name).name
            if not _has_any_suffix(Path(member_name), (".std", ".stdf", ".std.gz", ".stdf.gz", ".std.xz", ".stdf.xz", ".std.bz2", ".stdf.bz2")):
                continue

            target_path = destination / member_name
            if target_path.exists():
                stem = target_path.stem
                suffix = "".join(target_path.suffixes)
                counter = 1
                while True:
                    candidate = destination / f"{stem}__{counter}{suffix}"
                    if not candidate.exists():
                        target_path = candidate
                        break
                    counter += 1

            source_handle = archive.extractfile(member)
            if source_handle is None:
                continue

            with source_handle, target_path.open("wb") as target_handle:
                target_handle.write(source_handle.read())

            extracted.append(target_path)
    return extracted


def _progress(percent: float, message: str) -> None:
    clamped = max(0.0, min(100.0, float(percent)))
    print(f"[{clamped:6.2f}%] {message}", flush=True)


def _input_display_name(info: SourceFileInfo) -> str:
    return info.csv_path.name if info.csv_path is not None else info.source_path.name


def _prepare_input_files(
    input_folder: Path,
    *,
    work_dir: Path,
    cache_dir: Path,
    progress_callback: Callable[[float, str], None] | None = None,
) -> list[SourceFileInfo]:
    candidates: list[SourceFileInfo] = []
    extraction_dir = work_dir / "extracted_archives"
    extraction_dir.mkdir(parents=True, exist_ok=True)

    files = [path for path in sorted(input_folder.iterdir(), key=lambda item: item.name.lower()) if path.is_file()]
    if MAX_FILES is not None:
        files = files[: int(MAX_FILES)]

    total_files = max(len(files), 1)
    for index, path in enumerate(files, start=1):
        if progress_callback is not None:
            progress_callback((index - 1) / total_files, f"Preparing input file {index}/{total_files}: {path.name}")

        if path.suffix.lower() == ".csv":
            insertion = _insertion_from_filename(path)
            if insertion is None:
                continue
            lot, wafer = _parse_filename_metadata(path, insertion)
            candidates.append(
                SourceFileInfo(
                    source_path=path,
                    csv_path=path,
                    source_kind="csv",
                    insertion=insertion.insertion,
                    insertion_type=insertion.insertion_type,
                    temperature_c=insertion.temperature_c,
                    lot=lot,
                    wafer=wafer,
                    base_name=_strip_known_suffixes(path.name),
                )
            )
            continue

        if _has_any_suffix(path, _DIRECT_STDF_SUFFIXES):
            insertion = _insertion_from_filename(path)
            if insertion is None:
                continue
            if progress_callback is not None:
                file_start = (index - 1) / total_files
                file_span = 1 / total_files
                direct_power_data = _load_or_collect_target_power_data(
                    path,
                    cache_dir=cache_dir,
                    progress_callback=lambda fraction, message, file_start=file_start, file_span=file_span: progress_callback(
                        file_start + (file_span * fraction),
                        message,
                    ),
                )
            else:
                direct_power_data = _load_or_collect_target_power_data(path, cache_dir=cache_dir)
            lot, wafer = _parse_filename_metadata(path, insertion)
            candidates.append(
                SourceFileInfo(
                    source_path=path,
                    csv_path=None,
                    source_kind="stdf-direct",
                    insertion=insertion.insertion,
                    insertion_type=insertion.insertion_type,
                    temperature_c=insertion.temperature_c,
                    lot=lot,
                    wafer=wafer,
                    base_name=_strip_known_suffixes(path.name),
                    direct_power_data=direct_power_data,
                )
            )
            continue

        if _has_any_suffix(path, _TAR_STDF_SUFFIXES):
            with tempfile.TemporaryDirectory(prefix="txpa_txlo_stdf_") as temp_dir:
                extracted_members = _extract_stdf_members_from_tar(path, Path(temp_dir))
                for extracted in extracted_members:
                    insertion = _insertion_from_filename(extracted)
                    if insertion is None:
                        continue
                    if progress_callback is not None:
                        file_start = (index - 1) / total_files
                        file_span = 1 / total_files
                        direct_power_data = _load_or_collect_target_power_data(
                            extracted,
                            cache_dir=cache_dir,
                            cache_extra_key=f"{path.resolve()}::{extracted.name}",
                            progress_callback=lambda fraction, message, file_start=file_start, file_span=file_span: progress_callback(
                                file_start + (file_span * fraction),
                                message,
                            ),
                        )
                    else:
                        direct_power_data = _load_or_collect_target_power_data(
                            extracted,
                            cache_dir=cache_dir,
                            cache_extra_key=f"{path.resolve()}::{extracted.name}",
                        )
                    lot, wafer = _parse_filename_metadata(extracted, insertion)
                    candidates.append(
                        SourceFileInfo(
                            source_path=path,
                            csv_path=None,
                            source_kind="tar.gz-direct",
                            insertion=insertion.insertion,
                            insertion_type=insertion.insertion_type,
                            temperature_c=insertion.temperature_c,
                            lot=lot,
                            wafer=wafer,
                            base_name=_strip_known_suffixes(extracted.name),
                            direct_power_data=direct_power_data,
                        )
                    )

    return candidates


# -----------------------------------------------------------------------------
# Plotting
# -----------------------------------------------------------------------------


def _plot_temperature_cdf(
    *,
    out_path: Path,
    meta: TestMeta,
    insertion_infos: list[SourceFileInfo],
    series_by_insertion: dict[str, np.ndarray],
    limits_by_insertion: dict[str, tuple[float | None, float | None, str]],
    extrema_by_key: dict[tuple, dict[str, dict]],
) -> None:
    insertion_type = insertion_infos[0].insertion_type
    order = _INSERTION_ORDER_FE if insertion_type == "FE" else _INSERTION_ORDER_BE

    n_cols = len(order)
    fig, axes = plt.subplots(1, n_cols, figsize=(5.6 * n_cols, 6.2), sharey=True)
    if n_cols == 1:
        axes = [axes]

    title_bits = [f"T{meta.test_number}", meta.test_name]
    if meta.kind == "TXLO" and meta.lo_idac is not None:
        title_bits.append(f"LO IDAC {meta.lo_idac}")
    if meta.kind == "TXPA" and meta.lut_value is not None:
        title_bits.append(f"LUT {meta.lut_value}")
    if meta.frequency_ghz is not None:
        title_bits.append(f"{meta.frequency_ghz} GHz")
    if meta.pa_channel:
        title_bits.append(meta.pa_channel)
    fig.suptitle(" | ".join(title_bits))

    unit_for_axis = "dBm"

    for ax, insertion in zip(axes, order, strict=False):
        ax.grid(True, alpha=0.25)
        ax.set_xlabel("Power")
        if insertion == order[0]:
            ax.set_ylabel("CDF")

        values = series_by_insertion.get(insertion)
        if values is None or values.size == 0:
            ax.set_title(f"{insertion} / {_TEMP_BY_INS[insertion]}°C\nno data")
            continue

        x, y = _cdf_xy(values)
        if x.size == 0:
            ax.set_title(f"{insertion} / {_TEMP_BY_INS[insertion]}°C\nno valid data")
            continue

        source_rows = [row for row in insertion_infos if row.insertion == insertion]
        wafers = sorted({row.wafer for row in source_rows if row.wafer})
        lots = sorted({row.lot for row in source_rows if row.lot})

        extrema_tag = ""
        is_min = False
        is_max = False
        line_color = INSERTION_COLORS[insertion]
        if meta.kind == "TXLO" and meta.lo_idac == int(TARGET_TXLO_LO_IDAC) and meta.frequency_ghz in EXTREMA_FREQS:
            extrema_key = ("TXLO", int(meta.lo_idac))
            extrema_info = extrema_by_key.get(extrema_key, {})
            is_min = extrema_info.get("min", {}).get("test_number") == int(meta.test_number) and extrema_info.get("min", {}).get("insertion") == insertion
            is_max = extrema_info.get("max", {}).get("test_number") == int(meta.test_number) and extrema_info.get("max", {}).get("insertion") == insertion
        elif meta.kind == "TXPA" and meta.lut_value == int(TARGET_TXPA_LUT) and meta.frequency_ghz in EXTREMA_FREQS:
            extrema_key = ("TXPA", insertion_type, (meta.pa_channel or "ALL").strip().upper() or "ALL")
            extrema_info = extrema_by_key.get(extrema_key, {})
            is_min = extrema_info.get("min", {}).get("test_number") == int(meta.test_number) and extrema_info.get("min", {}).get("insertion") == insertion
            is_max = extrema_info.get("max", {}).get("test_number") == int(meta.test_number) and extrema_info.get("max", {}).get("insertion") == insertion

        if is_min:
            extrema_tag = " [MIN median]"
            line_color = HIGHLIGHT_MIN_COLOR
        elif is_max:
            extrema_tag = " [MAX median]"
            line_color = HIGHLIGHT_MAX_COLOR

        label = f"n={values.size}, wafers={max(len(wafers), 1)}{extrema_tag}"
        ax.scatter(
            x,
            y,
            color=line_color,
            s=20 if (is_min or is_max) else 12,
            marker="o",
            edgecolors=line_color,
            facecolors="none" if not (is_min or is_max) else line_color,
            linewidths=1.0 if (is_min or is_max) else 0.8,
            label=label,
        )

        low, high, unit = limits_by_insertion.get(insertion, (None, None, ""))
        unit_for_axis = unit or unit_for_axis
        limit_handles_added = False
        if low is not None:
            ax.axvline(low, color="red", linestyle="-", linewidth=1.2, alpha=0.9)
            limit_handles_added = True
        if high is not None:
            ax.axvline(high, color="red", linestyle="-", linewidth=1.2, alpha=0.9)
            limit_handles_added = True

        stats_text = (
            f"mean={np.mean(values):.3f}\n"
            f"med={_median(values):.3f}\n"
            f"std={np.std(values):.3f}\n"
            f"wafers={','.join(wafers) if wafers else '-'}\n"
            f"lots={','.join(lots) if lots else '-'}"
        )
        ax.text(
            0.02,
            0.98,
            stats_text,
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=7,
            family="monospace",
            bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "alpha": 0.78, "edgecolor": "none"},
        )
        ax.set_title(f"{insertion} / {_TEMP_BY_INS[insertion]}°C{extrema_tag}")
        if limit_handles_added:
            ax.plot([], [], color="red", linestyle="-", linewidth=1.2, label=f"Limits [{low:.3f}, {high:.3f}] {unit_for_axis}")
        else:
            ax.plot([], [], color="red", linestyle="-", linewidth=1.2, label="Limits [missing]")
        ax.legend(loc="lower right", fontsize=8, framealpha=0.9)

    for ax in axes:
        ax.set_xlabel(f"Power [{unit_for_axis or 'dBm'}]")

    fig.tight_layout(rect=[0, 0.02, 1, 0.93])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=PLOT_DPI)
    plt.close(fig)


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------


def main() -> int:
    input_folder = Path(INPUT_FOLDER)
    if not input_folder.exists():
        raise SystemExit(f"Input folder not found: {input_folder}")

    _progress(0, f"Starting TXPA/TXLO report generation from {input_folder}")

    run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_root = input_folder / "Outputs" / f"txpa_txlo_power_cdf_{run_tag}"
    artifacts_dir = output_root / "Artifacts"
    plots_dir = output_root / "cdf_plots"
    cache_dir = input_folder / "Outputs" / "_txpa_txlo_cache"
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    plots_dir.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)
    _progress(5, f"Created output folders under {output_root}")

    with tempfile.TemporaryDirectory(prefix="txpa_txlo_work_") as temp_work_dir:
        temp_work_path = Path(temp_work_dir)
        conversion_work_dir = temp_work_path / "conversion_work"

        _progress(10, "Preparing input files")
        input_files = _prepare_input_files(
            input_folder,
            work_dir=conversion_work_dir,
            cache_dir=cache_dir,
            progress_callback=lambda fraction, message: _progress(
                10 + (20 * fraction),
                message,
            ),
        )
        if not input_files:
            raise SystemExit(f"No supported input files found in: {input_folder}")

        _progress(32, f"Prepared {len(input_files)} input file(s) for analysis")

        txlo_factor: dict[tuple[int, int, int, int], float] = {}
        txlo_limits: dict[tuple[int, int, int], dict[str, tuple[float, float, str]]] = {}
        txpa_factor_fe: dict[tuple[int, int, int, str], float] = {}
        txpa_factor_be: dict[tuple[int, int, int, str], float] = {}
        txpa_limits_fe: dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]] = {}
        txpa_limits_be: dict[tuple[int, int, int, str], dict[str, tuple[float, float, str]]] = {}

        if ENABLE_PRE_CORRELATION:
            _progress(36, "Loading correlation factors and limits")
            required = [TXLO_CORR_XLSX_FE, TXPA_CORR_XLSX_FE, TXPA_CORR_XLSX_BE]
            missing = [str(path) for path in required if not path.exists()]
            if missing:
                raise FileNotFoundError("Correlation files are missing:\n- " + "\n- ".join(missing))
            txlo_factor, txlo_limits = _load_txlo_factors_and_limits()
            txpa_factor_fe, txpa_limits_fe = _load_txpa_factors_and_limits_fe()
            txpa_factor_be, txpa_limits_be = _load_txpa_factors_and_limits_be()
        else:
            _progress(36, "Skipping correlation-factor loading")

        source_rows: list[dict] = []
        test_name_by_num: dict[int, str] = {}
        raw_limits_by_ins_test: dict[tuple[str, int], list[tuple[float | None, float | None, str]]] = {}
        arrays_by_ins_test: dict[tuple[str, int], list[np.ndarray]] = {}
        meta_by_test: dict[int, TestMeta] = {}
        outlier_rows: list[dict] = []
        missing_factor_rows: list[dict] = []
        missing_limit_rows: list[dict] = []

        target_tests: set[int] = set()
        limits_cache_by_file: dict[Path, dict[int, tuple[float | None, float | None, str]]] = {}

        _progress(40, "Scanning prepared CSV metadata for target tests")
        total_inputs = max(len(input_files), 1)
        for index, info in enumerate(input_files, start=1):
            _progress(40 + (10 * index / total_inputs), f"Scanning metadata {index}/{total_inputs}: {_input_display_name(info)}")
            if info.direct_power_data is not None:
                name_map = dict(info.direct_power_data.name_map)
                limits_map = dict(info.direct_power_data.limits_map)
            elif info.csv_path is not None:
                name_map, limits_map = _read_flat_csv_metadata(info.csv_path)
                limits_cache_by_file[info.csv_path] = limits_map
            else:
                continue
            for test_number, test_name in name_map.items():
                meta = _parse_test_meta(test_number, test_name)
                if not _is_target_power_test(meta):
                    continue
                if not _is_selected_power_setting(meta):
                    continue
                raw_unit = limits_map.get(int(test_number), (None, None, ""))[2]
                if not _is_dbm_unit(raw_unit):
                    continue
                if TEST_NUMBER_FILTER and int(test_number) not in TEST_NUMBER_FILTER:
                    continue
                target_tests.add(int(test_number))
                test_name_by_num.setdefault(int(test_number), test_name)
                if meta is not None:
                    meta_by_test.setdefault(int(test_number), meta)

        if not target_tests:
            raise SystemExit("No TXLO/TXPA correlated-power style tests were found in the selected inputs.")

        _progress(52, f"Found {len(target_tests)} target test(s)")

        for index, info in enumerate(input_files, start=1):
            _progress(52 + (23 * index / total_inputs), f"Reading chip data {index}/{total_inputs}: {_input_display_name(info)}")
            direct_power_data = info.direct_power_data
            chip_matrix = None
            if direct_power_data is None:
                if info.csv_path is None:
                    continue
                chip_matrix, read_info = _read_flat_csv_chip_matrix(info.csv_path, tests_needed=target_tests)
                if read_info.get("error"):
                    continue
                if chip_matrix.empty:
                    continue

            source_rows.append(
                {
                    "source_file": str(info.source_path),
                    "csv_file": "" if info.csv_path is None else str(info.csv_path),
                    "source_kind": info.source_kind,
                    "lot": info.lot,
                    "wafer": info.wafer,
                    "insertion": info.insertion,
                    "insertion_type": info.insertion_type,
                    "temperature_c": info.temperature_c,
                    "n_chips": int(direct_power_data.n_chips if direct_power_data is not None else chip_matrix.shape[0]),
                }
            )

            if direct_power_data is not None:
                limits_map = dict(direct_power_data.limits_map)
                present_tests = sorted(set(direct_power_data.arrays_by_test).intersection(target_tests))
            else:
                limits_map = limits_cache_by_file.get(info.csv_path, {})
                present_tests = sorted(set(chip_matrix.columns).intersection(target_tests))
            for test_number in present_tests:
                if direct_power_data is not None:
                    arr = np.asarray(direct_power_data.arrays_by_test.get(int(test_number), np.array([], dtype=float)), dtype=float)
                else:
                    arr = pd.to_numeric(chip_matrix[int(test_number)], errors="coerce").dropna().to_numpy(dtype=float)
                if arr.size == 0:
                    continue

                filtered, removed = _filter_outliers_mad(arr, mad_multiplier=MAD_MULTIPLIER)
                if removed:
                    outlier_rows.append(
                        {
                            "source_file": str(info.source_path),
                            "csv_file": str(info.csv_path),
                            "insertion": info.insertion,
                            "test_number": int(test_number),
                            "n_before": int(arr.size),
                            "n_after": int(filtered.size),
                            "n_removed": int(removed),
                            "mad_multiplier": float(MAD_MULTIPLIER),
                        }
                    )
                if filtered.size == 0:
                    continue

                meta = meta_by_test.get(int(test_number))
                if meta is None:
                    continue

                analysis_values = filtered
                applied_factor = None
                limits_for_plot = limits_map.get(int(test_number), (None, None, ""))
                if not _is_dbm_unit(limits_for_plot[2]):
                    continue

                if ENABLE_PRE_CORRELATION:
                    if meta.kind == "TXLO" and meta.frequency_ghz is not None and meta.lo_idac is not None:
                        applied_factor = txlo_factor.get((int(test_number), int(meta.frequency_ghz), int(info.temperature_c), int(meta.lo_idac)))
                        corr_limit_map = txlo_limits.get((int(test_number), int(meta.frequency_ghz), int(meta.lo_idac)), {})
                        if info.insertion in corr_limit_map:
                            limits_for_plot = corr_limit_map[info.insertion]
                    elif meta.kind == "TXPA" and meta.frequency_ghz is not None and meta.lut_value is not None:
                        factor_lookup = txpa_factor_fe if info.insertion_type == "FE" else txpa_factor_be
                        limit_lookup = txpa_limits_fe if info.insertion_type == "FE" else txpa_limits_be
                        applied_factor = _lookup_txpa_factor(
                            factor_lookup,
                            lut=int(meta.lut_value),
                            freq=int(meta.frequency_ghz),
                            temp_c=int(info.temperature_c),
                            pa_channel=meta.pa_channel,
                        )
                        corr_limit_map = _lookup_txpa_limits(
                            limit_lookup,
                            test_number=int(test_number),
                            lut=int(meta.lut_value),
                            freq=int(meta.frequency_ghz),
                            pa_channel=meta.pa_channel,
                        )
                        if info.insertion in corr_limit_map:
                            limits_for_plot = corr_limit_map[info.insertion]

                    if applied_factor is not None:
                        analysis_values = filtered + float(applied_factor)
                    else:
                        missing_factor_rows.append(
                            {
                                "source_file": str(info.source_path),
                                "insertion": info.insertion,
                                "test_number": int(test_number),
                                "test_name": meta.test_name,
                                "kind": meta.kind,
                                "frequency_ghz": meta.frequency_ghz,
                                "lut": meta.lut_value,
                                "lo_idac": meta.lo_idac,
                                "pa_channel": meta.pa_channel,
                            }
                        )

                    if limits_for_plot[0] is None and limits_for_plot[1] is None:
                        missing_limit_rows.append(
                            {
                                "source_file": str(info.source_path),
                                "insertion": info.insertion,
                                "test_number": int(test_number),
                                "test_name": meta.test_name,
                                "kind": meta.kind,
                                "frequency_ghz": meta.frequency_ghz,
                                "lut": meta.lut_value,
                                "lo_idac": meta.lo_idac,
                                "pa_channel": meta.pa_channel,
                            }
                        )

                arrays_by_ins_test.setdefault((info.insertion, int(test_number)), []).append(analysis_values)
                raw_limits_by_ins_test.setdefault((info.insertion, int(test_number)), []).append(limits_for_plot)

        _progress(78, "Merging insertion-level series")
        merged_series_by_ins_test: dict[tuple[str, int], np.ndarray] = {}
        for key, parts in arrays_by_ins_test.items():
            if parts:
                merged_series_by_ins_test[key] = np.concatenate(parts)

        _progress(82, "Computing extrema summaries")
        extrema_candidates: dict[tuple, list[dict]] = {}
        for (insertion, test_number), series in merged_series_by_ins_test.items():
            meta = meta_by_test.get(int(test_number))
            if meta is None or not _is_selected_power_setting(meta):
                continue
            if meta.frequency_ghz not in EXTREMA_FREQS:
                continue

            row = {
                "kind": meta.kind,
                "test_number": int(test_number),
                "test_name": meta.test_name,
                "insertion": insertion,
                "insertion_type": _INS_TYPE_BY_INS[insertion],
                "temp_c": _TEMP_BY_INS[insertion],
                "freq_ghz": meta.frequency_ghz,
                "median": float(_median(series)),
                "lut": meta.lut_value,
                "lo_idac": meta.lo_idac,
                "pa_channel": (meta.pa_channel or "ALL").strip().upper() or "ALL",
            }

            if meta.kind == "TXLO" and meta.lo_idac == int(TARGET_TXLO_LO_IDAC):
                extrema_candidates.setdefault(("TXLO", int(meta.lo_idac)), []).append(row)
            elif meta.kind == "TXPA" and meta.lut_value == int(TARGET_TXPA_LUT):
                extrema_candidates.setdefault(("TXPA", _INS_TYPE_BY_INS[insertion], row["pa_channel"]), []).append(row)

        extrema_by_key: dict[tuple, dict[str, dict]] = {}
        extrema_summary_rows: list[dict] = []
        for key, rows in extrema_candidates.items():
            valid_rows = [row for row in rows if np.isfinite(row["median"])]
            if not valid_rows:
                continue
            min_row = min(valid_rows, key=lambda row: float(row["median"]))
            max_row = max(valid_rows, key=lambda row: float(row["median"]))
            extrema_by_key[key] = {"min": min_row, "max": max_row}
            extrema_summary_rows.append(
                {
                    "key": str(key),
                    "kind": min_row["kind"],
                    "insertion_type": min_row["insertion_type"],
                    "lut": min_row["lut"],
                    "lo_idac": min_row["lo_idac"],
                    "pa_channel": min_row["pa_channel"],
                    "min_test_number": min_row["test_number"],
                    "min_freq_ghz": min_row["freq_ghz"],
                    "min_insertion": min_row["insertion"],
                    "min_temp_c": min_row["temp_c"],
                    "min_median": min_row["median"],
                    "max_test_number": max_row["test_number"],
                    "max_freq_ghz": max_row["freq_ghz"],
                    "max_insertion": max_row["insertion"],
                    "max_temp_c": max_row["temp_c"],
                    "max_median": max_row["median"],
                }
            )

        _progress(86, "Generating plots and aggregate summaries")
        summary_rows: list[dict] = []
        test_numbers = sorted({test_number for (_, test_number) in arrays_by_ins_test})
        total_tests = max(len(test_numbers), 1)
        for plot_index, test_number in enumerate(test_numbers, start=1):
            _progress(86 + (10 * plot_index / total_tests), f"Plotting test {plot_index}/{total_tests}: T{int(test_number)}")
            meta = meta_by_test.get(int(test_number))
            if meta is None:
                continue
            if not _is_selected_power_setting(meta):
                continue

            has_fe = any((ins, test_number) in arrays_by_ins_test for ins in _INSERTION_ORDER_FE)
            insertion_type = "FE" if has_fe else "BE"
            insertion_order = _INSERTION_ORDER_FE if insertion_type == "FE" else _INSERTION_ORDER_BE
            relevant_sources = [row for row in input_files if row.insertion_type == insertion_type]

            series_by_insertion: dict[str, np.ndarray] = {}
            limits_by_insertion: dict[str, tuple[float | None, float | None, str]] = {}
            for insertion in insertion_order:
                arrays = arrays_by_ins_test.get((insertion, int(test_number)), [])
                if arrays:
                    series = np.concatenate(arrays)
                    series_by_insertion[insertion] = series
                    limit_rows = raw_limits_by_ins_test.get((insertion, int(test_number)), [])
                    lows = [row[0] for row in limit_rows if row[0] is not None]
                    highs = [row[1] for row in limit_rows if row[1] is not None]
                    unit = next((row[2] for row in limit_rows if row[2]), "dBm")
                    limits_by_insertion[insertion] = (
                        min(lows) if lows else None,
                        max(highs) if highs else None,
                        unit,
                    )
                    source_subset = [row for row in relevant_sources if row.insertion == insertion]
                    summary_rows.append(
                        {
                            "test_number": int(test_number),
                            "test_name": meta.test_name,
                            "kind": meta.kind,
                            "frequency_ghz": meta.frequency_ghz,
                            "lut": meta.lut_value,
                            "lo_idac": meta.lo_idac,
                            "pa_channel": meta.pa_channel,
                            "insertion": insertion,
                            "temperature_c": _TEMP_BY_INS[insertion],
                            "n_values": int(series.size),
                            "mean": float(np.mean(series)),
                            "median": float(_median(series)),
                            "std": float(np.std(series)),
                            "low_limit": limits_by_insertion[insertion][0],
                            "high_limit": limits_by_insertion[insertion][1],
                            "unit": limits_by_insertion[insertion][2],
                            "lots": "|".join(sorted({row.lot for row in source_subset if row.lot})),
                            "wafers": "|".join(sorted({row.wafer for row in source_subset if row.wafer})),
                            "correlation_applied": bool(ENABLE_PRE_CORRELATION),
                        }
                    )

            if not series_by_insertion:
                continue

            out_name = f"{meta.kind}__T{int(test_number)}"
            if meta.frequency_ghz is not None:
                out_name += f"__{meta.frequency_ghz}GHz"
            if meta.kind == "TXLO" and meta.lo_idac is not None:
                out_name += f"__PowCo{meta.lo_idac}"
            if meta.kind == "TXPA" and meta.lut_value is not None:
                out_name += f"__FwLu{meta.lut_value}"
            if meta.pa_channel:
                out_name += f"__{meta.pa_channel}"

            _plot_temperature_cdf(
                out_path=plots_dir / insertion_type / f"{out_name}.png",
                meta=meta,
                insertion_infos=relevant_sources,
                series_by_insertion=series_by_insertion,
                limits_by_insertion=limits_by_insertion,
                extrema_by_key=extrema_by_key,
            )

        _progress(97, "Writing report outputs")
        pd.DataFrame(source_rows).to_csv(output_root / "processed_input_files.csv", index=False)
        pd.DataFrame(summary_rows).to_csv(output_root / "aggregated_series_summary.csv", index=False)
        if outlier_rows:
            pd.DataFrame(outlier_rows).to_csv(output_root / "outliers_removed_mad.csv", index=False)
        if missing_factor_rows:
            pd.DataFrame(missing_factor_rows).drop_duplicates().to_csv(output_root / "missing_correlation_factors.csv", index=False)
        if missing_limit_rows:
            pd.DataFrame(missing_limit_rows).drop_duplicates().to_csv(output_root / "missing_correlation_limits.csv", index=False)
        if extrema_summary_rows:
            pd.DataFrame(extrema_summary_rows).to_csv(output_root / "extrema_median_summary.csv", index=False)

    _progress(100, f"Done. Output: {output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
