input_folder: PROD_Data
output_folder: PROD_Data/Outputs
modules:
  - DPLL
yield_threshold: 100.0
cpk_low: 1.67
cpk_high: 20.0
outlier_mad_multiplier: 6.0
max_files: null
single_file: null
encoding: latin1
generate_correlation_report: false
correlation_methods:
  - pearson
  - spearman
pearson_abs_min_for_report: 0.85
wafermap_circle_area_mult: 1.0
